version: '3.8'

services:
  # start the db image and map to port 27017
  db:
    image: mongo
    restart: always
    ports: [27017:27017]
    volumes:
      - 'db:/data/db'

  web:
    # start up the web app image and map to localhost
    build: ./app
    restart: always
    ports: [80:3000]
    # set variable for db port
    environment:
      - DB_HOST=mongodb://db:27017/posts
    depends_on:
      - db